library(tidyverse)
# this is the master script for the difference calculations.
# this is based on the stimulus data (picturedata.csv)
picdat <- read_csv("picturedata.csv")
# we use hamming distance (number of differences between vectors)

# ----------------------------
# Helper: Hamming distance
# ----------------------------
hamming_dist <- function(x, y) {
  sum(x != y, na.rm = TRUE)
}

source("dtf_calculation.R")
source("dtaf_calculation.R")
source("dtn_calculation.R")
source("dtan_calculation.R")

# here we rename the columns generated by the scripts so they can be added in a master sheet
difftoprot <- difftoprot %>%
  select(-prototype_id) %>%
  rename(
    DTF = total_distance,
    DTF_color = color_distance,
    DTF_shape = shape_distance,
    DTF_arrng = arrangement_distance
  )

difftoprots <- difftoprots %>%
  rename(
    DTAF = mean_distance,
    DTAF_sum = sum_distance
  )

diffinnovs <- diffinnovs %>%
  rename(
    DTN = dmean,
    DTN_sum = dalls
  )

diffinnovs2 <- diffinnovs2 %>%
  rename(
    DTAN = dmean,
    DTAN_sum = dalls
  )

# join the tibbles together
difference_indices <- difftoprot %>%
  full_join(difftoprots,  by = c("stimulus_id", "type")) %>%
  full_join(diffinnovs,   by = c("stimulus_id", "type")) %>%
  full_join(diffinnovs2,  by = c("stimulus_id", "type"))
# move columns holding general info to the left
difference_indices <- difference_indices %>%
  relocate(stimulus_id, type, phase)
