jkwid <- as.data.table(read.csv("gnet-artnarr-elte202301_-_register.csv",encoding = "UTF-8", sep = ","))
jkwid$exclude <- 0
colnames(jkwid) <- c("datetime",                                                                                                                                                                        
                     "agree",                           
                     "NEPTUN",                                                                                                                                                          
                     "age",                                                                                                                                                                  
                     "gen",                                                                                                                                                                
                     "edu",                                                                                                                                       
                     "health",                                              
                     "sleepdur",                                                                                                                                                    
                     "coffee",                                                   
                     "smoking",                                                                                     
                     "psychoasubs",
                     "X1..tétel",                                                                                                                                                                        
                     "X2..tétel",                                                                                                                                                                        
                     "X3..tétel",                                                                                                                                                                        
                     "X4..tétel",                                                                                                                                                                        
                     "X5..tétel",                                                                                                                                                                        
                     "X6..tétel",                                                                                                                                                                        
                     "X7..tétel",                                                                                                                                                                        
                     "Tapasztalt.e.tudatos.álmot.és.ha.igen..milyen.gyakran.",                                                                                                                           
                     "....volt.tudatában.a.valóságtól.való.eltéréseknek..pl..bizarr.eseményeknek.vagy.helyzeteknek...",                                                                                  
                     "....volt.tudatában.annak..hogy.a.fizikai.teste.alszik.",                                                                                                                           
                     "....volt.tudatában.annak..hogy.az.álomtartalmak.közül.semmi.sem.valós.",                                                                                                           
                     "....gondolt.különböző.lehetőségekre..amelyeket.meg.tud.tenni.egy.álomban.",                                                                                                        
                     "....volt.képes.fenntartani.az.éberségét.a.kívánatos.időtartamig.",                                                                                                                 
                     "....volt.képes.saját.akaratából.megfigyelőként.szemlélni.az.álmot.",                                                                                                               
                     "....volt.képes.saját.akaratából.megváltoztatni.a.környezetet..pl..megváltoztatni.a.tájat..",                                                                                       
                     "....volt.birtokában.az.álomtest.teljes.irányításának..mozgások..cselekedetek..",                                                                                                   
                     "....tudott.dönteni.szabad.akaratból.egy.bizonyos.cselekedet.mellett.",                                                                                                             
                     "....volt.képes.végrehajtani.meghatározott.cselekményeket..pl..repülés..lebegés..álomkarakterekkel.való.beszélgetés..varázslás..sex..",                                             
                     "....voltak.jelen.repüléssel..lebegéssel..zuhanással.vagy.forgással.járó.témák..események.",                                                                                        
                     "....voltak.jelen.repüléssel..lebegéssel..zuhanással.vagy.forgással.járó.érzékletek.",                                                                                             
                     "Az.elmúlt.pár.hónapra.vonatkozóan..megközelítőleg.milyen.gyakran.sikerült.felidéznie.álmait.",                                                                                     
                     "exclude")
jkwid[health %in% c("színtévesztő vagyok","piros-zöld színtévesztő vagyok",
                    "ADHD","bipoláris affektív zavar"), exclude := 1]
healthEXC <- jkwid[exclude == 1,]
jkwid <- jkwid[exclude == 0,]
